_name_or_path:
    value: google-t5/t5-large
_wandb:
    value:
        cli_version: 0.23.1
        e:
            cfk18r0tmhwkdda1q0d4lmn2bignfwzj:
                args:
                    - --model_name_or_path
                    - google-t5/t5-large
                    - --do_eval
                    - --use_data_subset
                    - "False"
                    - --dataset_name
                    - squad_v2
                    - --context_column
                    - context
                    - --question_column
                    - question
                    - --answer_column
                    - answers
                    - --output_dir
                    - ./save/squad_t5-large/
                    - --per_device_eval_batch_size
                    - "1"
                    - --deploy_scenario
                    - "True"
                    - --use_synchronize
                    - "True"
                    - --overwrite_output_dir
                    - --predict_with_generate
                    - --max_seq_length
                    - "512"
                    - --use_early_exit
                    - "True"
                    - --exit_conf_type
                    - softmax
                    - --exit_conf_threshold
                    - "1.000"
                    - --exit_min_layer
                    - "12"
                    - --include_inputs_for_metrics
                    - "False"
                    - --use_auth_token
                    - "False"
                    - --type_vocab_reduct
                    - "True"
                    - --k
                    - "256"
                    - --context_condition
                    - a
                    - --run_zeroshot
                    - "N"
                codePath: calm/src/run_question_answering.py
                codePathLocal: src/run_question_answering.py
                cpu_count: 128
                cpu_count_logical: 128
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "3836626923520"
                        used: "275333496832"
                email: awynn13@jh.edu
                executable: /scratch/enalisn1/awynn/anaconda3/envs/calm_squad/bin/python
                git:
                    commit: 28239cfb25cff66d0471d74cd8ab7c753ab3234c
                    remote: https://github.com/andreawynn/llm-risk-control.git
                gpu: NVIDIA L40S
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-98fd5638-5ca1-485c-fcbf-4fd9cf66d024
                host: l01
                memory:
                    total: "811301126144"
                os: Linux-4.18.0-477.27.1.el8_8.x86_64-x86_64-with-glibc2.28
                program: /weka/scratch/enalisn1/awynn/llm-risk-control/calm/src/run_question_answering.py
                python: CPython 3.10.12
                root: /weka/scratch/enalisn1/awynn/llm-risk-control/calm
                slurm:
                    cluster_name: cluster
                    conf: /opt/mprov/slurm/24.11.6-test1/etc/slurm.conf
                    cpus_on_node: "13"
                    cpus_per_task: "13"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: enalisn1
                    job_cpus_per_node: "13"
                    job_end_time: "1768463710"
                    job_gid: "1035"
                    job_gpus: "1"
                    job_id: "765557"
                    job_name: calm_squad
                    job_nodelist: l01
                    job_num_nodes: "1"
                    job_partition: l40s
                    job_qos: normal
                    job_start_time: "1768420510"
                    job_uid: "2065"
                    job_user: awynn
                    jobid: "765557"
                    localid: "0"
                    mem_per_node: "76800"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: l01
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /weka/scratch/enalisn1/awynn/llm-risk-control/calm
                    submit_host: dsailogin
                    task_pid: "1857372"
                    tasks_per_node: "1"
                    topology_addr: l01
                    topology_addr_pattern: node
                    tres_per_task: cpu=13
                startedAt: "2026-01-14T19:55:18.452579Z"
                writerId: cfk18r0tmhwkdda1q0d4lmn2bignfwzj
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
                - 100
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
                - 100
            "3":
                - 7
                - 16
                - 62
                - 66
            "4": 3.10.12
            "5": 0.23.1
            "6": 4.28.1
            "12": 0.23.1
            "13": linux-x86_64
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - T5ForConditionalGeneration
auto_find_batch_size:
    value: false
bad_words_ids:
    value: null
begin_suppress_tokens:
    value: null
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: null
chunk_size_feed_forward:
    value: 0
copy_skipped_hidden_states:
    value: false
count_flops:
    value: false
cross_attention_hidden_size:
    value: null
d_ff:
    value: 4096
d_kv:
    value: 64
d_model:
    value: 1024
data_seed:
    value: None
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_pin_memory:
    value: true
dataset:
    value: squad_v2
ddp_bucket_cap_mb:
    value: None
ddp_find_unused_parameters:
    value: None
ddp_timeout:
    value: 1800
debug:
    value: '[]'
decoder_start_token_id:
    value: 0
deepspeed:
    value: None
dense_act_fn:
    value: relu
disable_tqdm:
    value: false
distill_layer_alpha:
    value: null
diversity_penalty:
    value: 0
do_eval:
    value: true
do_layer_transformation:
    value: false
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
dropout_rate:
    value: 0.1
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 1
eval_accumulation_steps:
    value: None
eval_batch_size:
    value: 1
eval_delay:
    value: 0
eval_steps:
    value: 500
evaluation_strategy:
    value: steps
exit_conf_threshold:
    value: 1
exit_conf_type:
    value: softmax
exit_min_layer:
    value: 12
exit_position_temp:
    value: null
exponential_decay_length_penalty:
    value: null
feed_forward_proj:
    value: relu
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: '[]'
fsdp_config:
    value: '{''fsdp_min_num_params'': 0, ''xla'': False, ''xla_fsdp_grad_ckpt'': False}'
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: None
full_determinism:
    value: false
generation_config:
    value: None
generation_max_length:
    value: None
generation_num_beams:
    value: None
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
greater_is_better:
    value: true
group_by_length:
    value: false
half_precision_backend:
    value: auto
hub_model_id:
    value: None
hub_private_repo:
    value: false
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_inputs_for_metrics:
    value: true
initializer_factor:
    value: 1
intermediate_loss_fn:
    value: null
is_decoder:
    value: false
is_encoder_decoder:
    value: true
is_gated_act:
    value: false
jit_mode_eval:
    value: false
k:
    value: 256
label_names:
    value: None
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
lambda_threshold:
    value: 1
layer_norm_epsilon:
    value: 1e-06
learning_rate:
    value: 5e-05
length_column_name:
    value: length
length_penalty:
    value: 1
load_best_model_at_end:
    value: true
local_rank:
    value: -1
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: ./save/squad_t5-large/runs/Jan14_14-55-17_l01
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 500
logging_strategy:
    value: steps
lora_alpha:
    value: 8
lora_dropout:
    value: 0.1
lora_rank:
    value: 8
lora_target_modules:
    value: null
lr_scheduler_type:
    value: linear
max_answer_length:
    value: 30
max_grad_norm:
    value: 1
max_length:
    value: 20
max_steps:
    value: -1
metric_for_best_model:
    value: f1
min_length:
    value: 0
model:
    value: google-t5/t5-large
model_type:
    value: t5
mp_parameters:
    value: ""
n_positions:
    value: 512
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_decoder_layers:
    value: 24
num_heads:
    value: 16
num_layers:
    value: 24
num_return_sequences:
    value: 1
num_train_epochs:
    value: 3
optim:
    value: adafactor
optim_args:
    value: None
output_attentions:
    value: false
output_dir:
    value: ./save/squad_t5-large/
output_hidden_states:
    value: false
output_hidden_states_decoder:
    value: false
output_past:
    value: true
output_scores:
    value: false
overwrite_output_dir:
    value: true
pad_token_id:
    value: 0
parallel_causal_mask:
    value: true
parallel_gen_token:
    value: true
past_index:
    value: -1
per_device_eval_batch_size:
    value: 1
per_device_train_batch_size:
    value: 8
per_gpu_eval_batch_size:
    value: None
per_gpu_train_batch_size:
    value: None
plotting_logits:
    value: false
predict_with_generate:
    value: true
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: None
push_to_hub_organization:
    value: None
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
relative_attention_max_distance:
    value: 128
relative_attention_num_buckets:
    value: 32
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
repetition_penalty:
    value: 1
report_to:
    value: '[''wandb'']'
resume_from_checkpoint:
    value: None
return_dict:
    value: true
return_dict_in_generate:
    value: false
rollback_conf_threshold:
    value: null
run_name:
    value: ./save/squad_t5-large/
save_on_each_node:
    value: false
save_safetensors:
    value: false
save_steps:
    value: 500
save_strategy:
    value: steps
save_total_limit:
    value: 1
seed:
    value: 42
sep_token_id:
    value: null
shallow_exit_layer:
    value: null
shallow2deep_conf_threshold:
    value: 1
shallow2deep_conf_type:
    value: null
sharded_ddp:
    value: '[]'
skip_memory_metrics:
    value: true
sortish_sampler:
    value: false
static_exit_layer:
    value: null
suppress_tokens:
    value: null
task_specific_params:
    value:
        summarization:
            early_stopping: true
            length_penalty: 2
            max_length: 200
            min_length: 30
            no_repeat_ngram_size: 3
            num_beams: 4
            prefix: 'summarize: '
        translation_en_to_de:
            early_stopping: true
            max_length: 300
            num_beams: 4
            prefix: 'translate English to German: '
        translation_en_to_fr:
            early_stopping: true
            max_length: 300
            num_beams: 4
            prefix: 'translate English to French: '
        translation_en_to_ro:
            early_stopping: true
            max_length: 300
            num_beams: 4
            prefix: 'translate English to Romanian: '
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: None
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: None
torch_compile_mode:
    value: None
torch_dtype:
    value: null
torchdynamo:
    value: None
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: None
train_batch_size:
    value: 8
train_meta_cm_head:
    value: false
transformers_version:
    value: 4.28.1
type_vocab_reduct:
    value: true
typical_p:
    value: 1
use_adapt_threshold:
    value: false
use_bfloat16:
    value: false
use_cache:
    value: true
use_early_exit:
    value: true
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_lora:
    value: false
use_mps_device:
    value: false
use_shallow_deep:
    value: false
use_synchronize:
    value: true
vocab_size:
    value: 32128
warmup_ratio:
    value: 0
warmup_steps:
    value: 0
weight_decay:
    value: 0
xpu_backend:
    value: None
